server:
  port: 8088


spring:
  datasource:                                           # 数据源的相关配置
   url: jdbc:mysql://192.168.127.188:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
   password: 123456

  redis:
    database: 1
    host: 192.168.127.188
    port: 6379
    password: 123456
mybatis:
    configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
